### ISSUE TITLE
Linux porting

### ISSUE THREAD

**Issue by zelytra** [zelytra/BetterFleet#350]
## Description of needs

Make BetterFleet work on Linux distributions. This feature is not in development (yet) and is still in discussion

## Tasks

* [ ] Generate Linux image with SOT running on it to test @zelytra 
* [ ] Tauri adaptation to generate Linux installer @zelytra 
* [ ] CI/CD adaptation to handle Linux release @zelytra 
* [ ] Change the method to retrieve UDP connection on Linux distro @dadodasyra 

## Notes
This issue may be splited into multiple MR

**Comment by zelytra** [comment]
### Problem:
When SoT is run under Wine, the **wineserver** process manages the emulated network stack instead of the game process itself. This complicates determining the specific network port and traffic associated with the game.

### Current Method:
1. Use `netstat` to identify the UDP port wineserver is listening on:
   ```bash
   netstat -4panu | grep wineserver
   ```
   Example output:
   ```
   udp 0 0 0.0.0.0:32796 0.0.0.0:* 31538/wineserver
   ```

2. Use a packet capture tool (e.g., `ngrep`) to monitor traffic on the identified port:
   ```bash
   sudo ngrep -W single -d any udp and dst port 32796
   ```
   Example output:
   ```
   U 172.166.255.146:30401 -> 192.168.1.11:32796 [network frame]
   ```

3. The need for **root permissions** to capture packets with tools like `ngrep` is noted as a limitation.

### Challenges:
- Wineserver handles all network-related tasks, so determining which wineserver instance corresponds to the specific game process can be ambiguous if multiple wineservers are running.
- The process requires administrative privileges for packet capture, which may not always be ideal.
- There's a potential for a less specific solution due to Proton's reliance on Wine.

### Context:
- Sea of Thieves is available on Windows via two platforms: Steam and the Xbox app. The Xbox app version relies on Microsoft Store DRM, making it incompatible with Linux.
- The Steam version is the only viable option, as it runs with Proton/Wine for Windows-to-Linux compatibility.

### Next Steps:
The author suggests exploring Wine documentation to determine if there's a way to link a wineserver to a specific Wine process. Additionally, they note that requiring administrative privileges for packet capture is also the norm on Windows. The discussion leans toward refining the solution for better specificity while acknowledging that the current approach is functional.

**Comment by dadodasyra** [comment]
Is it still a thing since linux doesnt even runs the game but emulate it under windows ?

**Comment by zelytra** [comment]
Here may be players on this platform even though the game was not originally designed for it. This issue can remain open in case the developer who offered to handle it revisits the matter or if other individuals become interested. In any case, we will keep a record of this issue for potential future porting.

**Comment by elegos** [comment]
Hello everyone,

I think I resolved the first of the two problems. I made a PoC in Python you can find [here](https://gist.github.com/elegos/23212d1ed889e6ca37a2641f5a4f7358).

Essentially: in the ps tree, wineserver is not a parent of SotGame.exe, though it's still a process part of the same tree.

`SotGame.exe`: systemd───systemd───bash───steam───reaper───srt-bwrap───pv-adverb───GameThread───2545*[{GameThread}]
`wineserver`: systemd───systemd───bash───steam───reaper───srt-bwrap───pv-adverb───wineserver

This allows an application to infer the wineserver associated to SotGame.exe.

This said, the PoC continues sniffing the UDP traffic (as the creator of the app might well know, UDP ports are stateless, differently from TCP, and thus connections are not bound to the other side of the line -> thus the sniffing). This requires root privileges, of the binary (in this case python, but might be aswell the `betterfleet` binary) to have some caps set. In the PoC example, they can be given via: `sudo setcap cap_net_raw,cap_net_admin=eip $(readlink -f $(which python3))`. I'm not a capabilities subject expert, so I don't know if they're saved across restarts (and thus the install script might give these capabilities to the binary), or it'd need something different.

**Comment by zelytra** [comment]
@elegos this deserved an answer a lot sooner than a year — sorry. I went and re-read the detection code against your PoC, and the short version is that you solved the part we were stuck on.

### Your process-tree finding is the unlock

The thing that kept this issue open was the ambiguity: *which* wineserver is the game's. Inferring it from the shared ancestor rather than from parentage settles it —

```
SotGame.exe: systemd───systemd───bash───steam───reaper───srt-bwrap───pv-adverb───GameThread
wineserver:  systemd───systemd───bash───steam───reaper───srt-bwrap───pv-adverb───wineserver
```

— and it holds up with several wineservers running, which was the specific worry in the first post. That was the open question, and it's answered.

### @dadodasyra's question, since it's a fair one

> Is it still a thing since linux doesn't even runs the game but emulate it under windows?

It doesn't change anything, and that's the useful part: the detection works at the network layer, and Proton doesn't touch what goes on the wire. What it changes is *which process owns the socket* — which is exactly what @elegos's PoC resolves.

### Where the code actually stands

`src-tauri/src/fetch_informations.rs` is 353 lines. **17 of them touch a Windows API.** Everything else is already portable:

- the game PID comes from `sysinfo` — cross-platform
- the UDP sockets come from `netstat2::get_sockets_info` — cross-platform
- the heuristic itself (SoT servers live in `[30000, 40000)`, rank candidate flows by packet volume within a capture window) is a pure function with unit tests

The one Windows-bound piece is `WSAIoctl(SIO_RCVALL)` — the promiscuous raw socket. The Linux equivalent is `AF_PACKET`/pcap. That's a swap behind a small abstraction, not a rewrite.

Worth knowing since it landed after this issue was filed: the "first plausible packet wins" approach is gone. Steam Datagram Relay broke it (#364) — the game opens 25+ sparse SDR sockets and the old code raced between them and latched onto the wrong one. It now sniffs every game UDP port for a window and takes the busiest plausible flow, because the real server pushes dozens of packets a second while the SDR sockets push almost none (#591). This matters for Linux specifically: the Steam build is the only one that runs under Proton — the Xbox/Store version's DRM won't — so **SDR is guaranteed** there, and the volume ranking is the reason that's already handled.

### On privileges — you're being harder on yourself than the situation deserves

> The need for **root permissions** to capture packets with tools like `ngrep` is noted as a limitation.

`build.rs` stamps `requireAdministrator` into the Windows manifest today. **The entire GUI already runs elevated on Windows**, for exactly this reason. `CAP_NET_RAW` on a small helper binary, with the app itself unprivileged, would be *strictly better* than what Windows users get right now. Your suggestion —

> a 10-lines C application or similar to be installed via distribution package (rpm, deb etc) in `/usr/lib/betterfleet/fleet-listener` with a post-install script which gives the right capabilities to it, and then call it as a subprocess

— is the right shape, and it's the shape we'd want on Windows too if we were starting over. (Capabilities set with `setcap` do persist on the file, so a postinst is enough; they're lost on replace, which is what the package manager does on upgrade — so the postinst has to run every time, not just on first install.)

### What actually blocks this, and it isn't the code

**Packaging, and it isn't a free choice.** The release matrix is `platform: [windows-latest]` and the bundle targets are `nsis` + `updater` — there's no Linux artifact at all today. And `setcap` decides the format for us: a `.deb`/`.rpm` postinst can set capabilities, an **AppImage cannot** — there's no install step. Tauri's updater on Linux wants an AppImage. So it's deb/rpm without auto-update, or AppImage plus a separately-installed helper. That's a real fork in the road and it's the first thing to settle.

**Maintenance.** Nobody here runs SoT on Linux, CI can't test it, and the heuristic has already had to be re-tuned once against real captures when SDR broke it. The next time Rare changes something, that needs a Linux player with a packet capture — not a one-off, an ongoing thing.

Which is to say: the code is the small part. If you're still interested, the honest framing is that this wants to be contributor-led — the port behind `#[cfg(target_os = "linux")]`, a deb/rpm marked experimental, and someone who plays on Linux willing to look when it drifts. If that's something you'd want to take on, I'm glad to review and to sort out the packaging side. And either way, thank you for digging into the wineserver problem — it's the piece we couldn't get past.

<sub>Analysis assembled with [Claude Code](https://claude.com/claude-code); the decisions are mine.</sub>

**Comment by zelytra** [comment]
**Re-sequenced (see #735).** The WebKit 4.0 retirement means the whole port now sits on a **Tauri v2 migration (#735)** as its prerequisite: v1 cannot build or run natively on modern/rolling distros (Arch/CachyOS, Fedora 40+, Ubuntu 24.04+) — including the dev machine. Order: **#735 first**, then the sub-issues below.

Packaging also changes: the .deb-only decision (#724) is **superseded** by a **max-distro** requirement (it must run on rolling distros / the dev box too, which a .deb cannot). Target formats become **AppImage / Flatpak**, which v2 (WebKit 4.1) makes native and, with a bundled runtime, durable.

**Comment by zelytra** [comment]
Shipped in 2.3.0. BetterFleet now runs on Linux: Tauri v2 migration, Sea of Thieves server detection under Proton via an AF_PACKET capture isolated in the privilege-separated betterfleet-netcap helper (#725, #726), the X11 overlay and set-sail auto-click with the Wayland limitation documented (#731/#743), browser-based OIDC loopback sign-in (#761), and .deb / .rpm / pacman packages. Closing as done.
